FROM maven:3.8-openjdk-17

WORKDIR /app

# 复制Maven配置
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

# 设置权限
RUN chmod +x mvnw

# 热启动模式，使用本地源代码
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"] 