FROM maven:3.9-eclipse-temurin-17 AS development

WORKDIR /app

# 复制 Maven 配置文件
COPY ./pom.xml .
COPY ./.mvn ./.mvn
COPY ./mvnw .
COPY ./mvnw.cmd .

# 复制源代码
COPY ./src ./src

# Spring Boot 开发模式
# 使用 spring-boot-devtools 进行热重载
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-XX:TieredStopAtLevel=1 -Xmx1G'"] 